### PR TITLE
Update debian copyright file

### PR DESCRIPTION
**Pull request by jvalleroy**
Based on upstream v0.8.0, but modified to follow Debian's standard format.

### CODE REVIEW

**Comment by nodiscc** [comment]
Thanks. How did you generate the copyright file? (looking to know more about debian packaging)

**Comment by jvalleroy** [comment]
It wasn't generated, unfortunately. I started with the upstream file and made a lot of changes manually, following https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/.

I see there are some tools available (mentioned at https://wiki.debian.org/CopyrightReviewTools) but I'm not familiar with them yet.

**Comment by virtualtam** [comment]
@nodiscc @jvalleroy maybe we can adopt this format in the base repository? We could make such files more easily parseable/processable to Debian packaging scripts.

I could give a hand to integrate checks in CI (Travis, lintian & co), it's been a while since I haven't done any Debian packaging though :)

**Comment by nodiscc** [comment]
> maybe we can adopt this format in the base repository?

I'm all for it, the current COPYING file was already a manual attempt to mimic a Debian `copyright` file. Let's replace it with @jvalleroy's version?

> CI
> lintian

👍 👍 👍

**Pull request merged**
